name: LeeesNetherFix
version: 2.0
api-version: 1.16
main: Leees.nether.fix.Main
author: Nate Legault
description: kills players when they go under or above the nether

permissions:
  nether.bypass:
    description: Allow players under or above the nether.