# Configuration file for LeeesNetherFix Version 1.2

# What is the top layer of the nether?
# In other words, what is the y-coodinate
# of the nethers uppermost bedrock?
# default: netherTopLayer: 126 netherBottomLayer: 1
netherTopLayer: 126
netherBottomLayer: 1
# What message should be displayed when players
# attempt to go to the top of the nether?
# default: netherTopMessage: '&cThe top of the nether are both disabled'
netherTopMessage: '&cUnder and above the nether are both disabled'